/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-Aug-2020 4:13:02 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS 'CSFSP80053View'
;

DROP VIEW IF EXISTS 'CSFView'
;

DROP VIEW IF EXISTS 'SP80053View'
;

/* Drop Tables */

DROP TABLE IF EXISTS 'CSFCategory'
;

DROP TABLE IF EXISTS 'CSFFunction'
;

DROP TABLE IF EXISTS 'CSFSP80053'
;

DROP TABLE IF EXISTS 'CSFSubcategory'
;

DROP TABLE IF EXISTS 'SP80053Control'
;

DROP TABLE IF EXISTS 'SP80053ControlClass'
;

DROP TABLE IF EXISTS 'SP80053ControlDetail'
;

DROP TABLE IF EXISTS 'SP80053ControlFamily'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'CSFCategory'
(
	'CSFCategoryIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFID' TEXT NOT NULL,
	'CSFFunctionCategoryID' TEXT NOT NULL,
	'CSFCategoryID' TEXT NOT NULL,
	'CSFCategoryName' TEXT NOT NULL,
	'CSFCategoryDescription' TEXT NOT NULL,
	'CSFFunctionIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_CSFCategory_CSFFunction' FOREIGN KEY ('CSFFunctionIndex') REFERENCES 'CSFFunction' ('CSFFunctionIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'CSFFunction'
(
	'CSFFunctionIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFID' TEXT NOT NULL,
	'CSFFunctionID' TEXT NOT NULL,
	'CSFFunctionName' TEXT NOT NULL,
	'CSFFunctionDescription' TEXT NOT NULL
)
;

CREATE TABLE 'CSFSP80053'
(
	'CSFSP80053Index' INTEGER NOT NULL PRIMARY KEY,
	'CSFSubcategoryIndex' INTEGER NOT NULL,
	'CSFID' TEXT NOT NULL,
	'SP80053ControlDetailIndex' INTEGER NOT NULL,
	'SP80053ID' TEXT NOT NULL,
	CONSTRAINT 'FK_CSFSP80053CW_CSFSubcategory' FOREIGN KEY ('CSFSubcategoryIndex') REFERENCES 'CSFSubcategory' ('CSFSubcategoryIndex') ON DELETE Set Null ON UPDATE Cascade,
	CONSTRAINT 'FK_CSFSP80053CW_SP80053ControlDetail' FOREIGN KEY ('SP80053ControlDetailIndex') REFERENCES 'SP80053ControlDetail' ('SP80053ControlDetailIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'CSFSubcategory'
(
	'CSFSubcategoryIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFID' TEXT NOT NULL,
	'CSFFunctionCategorySubcategoryID' TEXT NOT NULL,
	'CSFSubcategoryID' INTEGER NOT NULL,
	'CSFSubcategoryDescription' TEXT NOT NULL,
	'CSFCategoryIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_CSFSubcategory_CSFCategory' FOREIGN KEY ('CSFCategoryIndex') REFERENCES 'CSFCategory' ('CSFCategoryIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'SP80053Control'
(
	'SP80053ControlIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053ControlFamilyControlID' TEXT NOT NULL,
	'SP80053ControlID' INTEGER NOT NULL,
	'SP80053ControlName' TEXT NOT NULL,
	'SP80053ControlFamilyIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053Control_SP80053ControlFamily' FOREIGN KEY ('SP80053ControlFamilyIndex') REFERENCES 'SP80053ControlFamily' ('SP80053ControlFamilyIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'SP80053ControlClass'
(
	'SP80053ControlClassIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ControlClassID' INTEGER NOT NULL,
	'SP80053ControlClassName' TEXT NOT NULL
)
;

CREATE TABLE 'SP80053ControlDetail'
(
	'SP80053ControlDetailIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053ControlFamilyControlDetailID' TEXT NULL,
	'SP80053ControlDetailID' TEXT NOT NULL,
	'SP80053ControlDetailSubtitle' TEXT NULL,
	'SP80053ControlDetailDescription' TEXT NOT NULL,
	'SP80053ControlDetailPriority' INTEGER NULL,
	'SP80053ControlDetailAssurance' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineLow' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineMod' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineHigh' INTEGER NOT NULL,
	'SP80053ControlIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053ControlDetail_SP80053Control' FOREIGN KEY ('SP80053ControlIndex') REFERENCES 'SP80053Control' ('SP80053ControlIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'SP80053ControlFamily'
(
	'SP80053ControlFamilyIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053ControlFamilyID' TEXT NOT NULL,
	'SP80053ControlFamilyName' TEXT NOT NULL,
	'SP80053ControlFamilyFIPS200MinReq' TEXT NULL,
	'SP80053ControlClassIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053ControlFamily_SP80053ControlClass' FOREIGN KEY ('SP80053ControlClassIndex') REFERENCES 'SP80053ControlClass' ('SP80053ControlClassIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_CSFCategory_CSFFunction'
 ON 'CSFCategory' ('CSFFunctionIndex' ASC)
;

CREATE INDEX 'IXFK_CSFSP80053CW_CSFSubcategory'
 ON 'CSFSP80053' ('CSFSubcategoryIndex' ASC)
;

CREATE INDEX 'IXFK_CSFSP80053CW_SP80053ControlDetail'
 ON 'CSFSP80053' ('SP80053ControlDetailIndex' ASC)
;

CREATE INDEX 'IXFK_CSFSubcategory_CSFCategory'
 ON 'CSFSubcategory' ('CSFCategoryIndex' ASC)
;

CREATE INDEX 'IXFK_SP80053Control_SP80053ControlFamily'
 ON 'SP80053Control' ('SP80053ControlFamilyIndex' ASC)
;

CREATE INDEX 'IXFK_SP80053ControlDetail_SP80053Control'
 ON 'SP80053ControlDetail' ('SP80053ControlIndex' ASC)
;

CREATE INDEX 'IXFK_SP80053ControlFamily_SP80053ControlClass'
 ON 'SP80053ControlFamily' ('SP80053ControlClassIndex' ASC)
;

/* Create Views */

CREATE VIEW 'CSFSP80053View' AS 
SELECT CSFFunctionName,
       CSFCategoryName,
       CSFSubcategoryDescription,
       SP80053ControlFamilyName,
       SP80053ControlFamilyFIPS200MinReq,
       SP80053ControlName,
       SP80053ControlDetailDescription,
       SP80053ControlDetailPriority,
       SP80053ControlDetailBaselineLow,
       SP80053ControlDetailBaselineMod,
       SP80053ControlDetailBaselineHigh
  FROM CSFView
       LEFT JOIN
       CSFSP80053 ON CSFView.CSFSubcategoryIndex = CSFSP80053.CSFSubcategoryIndex
       LEFT JOIN
       SP80053View ON CSFSP80053.SP80053ControlDetailIndex = SP80053View.SP80053ControlDetailIndex
 WHERE SP80053ControlFamilyName IS NOT NULL
 ORDER BY SP80053ControlName
;


CREATE VIEW 'CSFView' AS 
SELECT CSFSubcategory.CSFSubcategoryIndex,
       CSFFunctionName,
       CSFFunction.CSFFunctionID,
       CSFCategoryName,
       CSFCategory.CSFFunctionCategoryID,
       CSFSubcategoryDescription,
       CSFSubcategory.CSFFunctionCategorySubcategoryID
  FROM CSFFunction
       INNER JOIN
       CSFCategory ON CSFFunction.CSFFunctionIndex = CSFCategory.CSFFunctionIndex
       INNER JOIN
       CSFSubcategory ON CSFCategory.CSFCategoryIndex = CSFSubcategory.CSFCategoryIndex
 ORDER BY CSFFunction.CSFFunctionIndex,
          CSFCategoryName ASC
;


CREATE VIEW 'SP80053View' AS 
SELECT SP80053ControlDetailIndex,
       SP80053ControlFamily.SP80053ControlFamilyID,
       SP80053ControlFamilyName,
       SP80053ControlFamilyFIPS200MinReq,
       SP80053Control.SP80053ControlFamilyControlID,
       SP80053ControlName,
       SP80053ControlDetail.SP80053ControlDetailID,
       SP80053ControlDetailDescription,
       SP80053ControlDetailPriority,
       SP80053ControlDetailBaselineLow,
       SP80053ControlDetailBaselineMod,
       SP80053ControlDetailBaselineHigh
  FROM SP80053ControlFamily
       INNER JOIN
       SP80053Control ON SP80053ControlFamily.SP80053ControlFamilyIndex = SP80053Control.SP80053ControlFamilyIndex
       INNER JOIN
       SP80053ControlDetail ON SP80053Control.SP80053ControlIndex = SP80053ControlDetail.SP80053ControlIndex
 WHERE SP80053ControlDetailDescription != ""
 ORDER BY SP80053ControlFamilyName,
          SP80053ControlName ASC
;

