/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 11-Aug-2020 7:23:04 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'RMFStep'
;

DROP TABLE IF EXISTS 'RMFTask'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'RMFStep'
(
	'RMFStepIndex' INTEGER NOT NULL PRIMARY KEY,
	'RMFID' TEXT NOT NULL,
	'RMFStep' TEXT NOT NULL,
	'RMFStepID' INTEGER NOT NULL,
	'RMFStepDescription' TEXT NOT NULL
)
;

CREATE TABLE 'RMFTask'
(
	'RMFTaskIndex' INTEGER NOT NULL PRIMARY KEY,
	'RMFID' TEXT NOT NULL,
	'RMFTaskID' TEXT NOT NULL,
	'RMFTask' TEXT NOT NULL,
	'RMFTaskDescription' TEXT NOT NULL,
	'RMFTaskTier' TEXT NULL,
	'RMFStepIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_RMFTask_RMFStep' FOREIGN KEY ('RMFStepIndex') REFERENCES 'RMFStep' ('RMFStepIndex') ON DELETE No Action ON UPDATE No Action
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_RMFTask_RMFStep'
 ON 'RMFTask' ('RMFStepIndex' ASC)
;
