/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 11-Aug-2020 7:53:09 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS 'RMFView'
;

/* Create Views */

CREATE VIEW 'RMFView' AS 
SELECT RMFTaskIndex,
       RMFTask.RMFID,
       RMFStepID,
       RMFStep,
       RMFStepDescription,
       RMFTask,
       RMFTaskDescription,
       RMFTaskTier
  FROM RMFStep
       INNER JOIN
       RMFTask ON RMFStep.RMFStepIndex = RMFTask.RMFStepIndex
;

