/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-Aug-2020 3:33:51 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'CSFCategory'
;

DROP TABLE IF EXISTS 'CSFFunction'
;

DROP TABLE IF EXISTS 'CSFSubcategory'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'CSFCategory'
(
	'CSFCategoryIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFID' TEXT NOT NULL,
	'CSFFunctionCategoryID' TEXT NOT NULL,
	'CSFCategoryID' TEXT NOT NULL,
	'CSFCategoryName' TEXT NOT NULL,
	'CSFCategoryDescription' TEXT NOT NULL,
	'CSFFunctionIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_CSFCategory_CSFFunction' FOREIGN KEY ('CSFFunctionIndex') REFERENCES 'CSFFunction' ('CSFFunctionIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'CSFFunction'
(
	'CSFFunctionIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFID' TEXT NOT NULL,
	'CSFFunctionID' TEXT NOT NULL,
	'CSFFunctionName' TEXT NOT NULL,
	'CSFFunctionDescription' TEXT NOT NULL
)
;

CREATE TABLE 'CSFSubcategory'
(
	'CSFSubcategoryIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFID' TEXT NOT NULL,
	'CSFFunctionCategorySubcategoryID' TEXT NOT NULL,
	'CSFSubcategoryID' INTEGER NOT NULL,
	'CSFSubcategoryDescription' TEXT NOT NULL,
	'CSFCategoryIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_CSFSubcategory_CSFCategory' FOREIGN KEY ('CSFCategoryIndex') REFERENCES 'CSFCategory' ('CSFCategoryIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_CSFCategory_CSFFunction'
 ON 'CSFCategory' ('CSFFunctionIndex' ASC)
;

CREATE INDEX 'IXFK_CSFSubcategory_CSFCategory'
 ON 'CSFSubcategory' ('CSFCategoryIndex' ASC)
;
