/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-Aug-2020 2:34:47 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS 'SP80053View'
;

/* Create Views */

CREATE VIEW 'SP80053View' AS 
SELECT SP80053ControlDetailIndex,
       SP80053ControlFamily.SP80053ControlFamilyID,
       SP80053ControlFamilyName,
       SP80053ControlFamilyFIPS200MinReq,
       SP80053Control.SP80053ControlFamilyControlID,
       SP80053ControlName,
       SP80053ControlDetail.SP80053ControlDetailID,
       SP80053ControlDetailDescription,
       SP80053ControlDetailPriority,
       SP80053ControlDetailBaselineLow,
       SP80053ControlDetailBaselineMod,
       SP80053ControlDetailBaselineHigh
  FROM SP80053ControlFamily
       INNER JOIN
       SP80053Control ON SP80053ControlFamily.SP80053ControlFamilyIndex = SP80053Control.SP80053ControlFamilyIndex
       INNER JOIN
       SP80053ControlDetail ON SP80053Control.SP80053ControlIndex = SP80053ControlDetail.SP80053ControlIndex
 WHERE SP80053ControlDetailDescription != ""
 ORDER BY SP80053ControlFamilyName,
          SP80053ControlName ASC
;

