/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 11-Aug-2020 4:22:14 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'SP80053ControlDetail'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'SP80053ControlDetail'
(
	'SP80053ControlDetailIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053ControlFamilyControlDetailID' TEXT NULL,
	'SP80053ControlDetailID' TEXT NOT NULL,
	'SP80053ControlDetailEnhancement' INTEGER NOT NULL,
	'SP80053ControlDetailEnhancementID' TEXT NULL,
	'SP80053ControlDetailEnhancementTitle' TEXT NULL,
	'SP80053ControlDetailDescription' TEXT NOT NULL,
	'SP80053ControlDetailAssignment' TEXT NULL,
	'SP800ControlDetailTier' TEXT NULL,
	'SP80053ControlDetailDesignation' TEXT NULL,
	'SP80053ControlDetailSupplementalGuidance' TEXT NULL,
	'SP80053ControlDetailReference' TEXT NULL,
	'SP80053ControlDetailPriority' INTEGER NULL,
	'SP80053ControlDetailAssurance' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineLow' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineMod' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineHigh' INTEGER NOT NULL,
	'SP80053ControlIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053ControlDetail_SP80053Control' FOREIGN KEY ('SP80053ControlIndex') REFERENCES 'SP80053Control' ('SP80053ControlIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_SP80053ControlDetail_SP80053Control'
 ON 'SP80053ControlDetail' ('SP80053ControlIndex' ASC)
;
