/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 06-Aug-2020 8:48:11 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS 'SP80053Control'
;

DROP TABLE IF EXISTS 'SP80053ControlClass'
;

DROP TABLE IF EXISTS 'SP80053ControlDetail'
;

DROP TABLE IF EXISTS 'SP80053ControlFamily'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'SP80053Control'
(
	'SP80053ControlIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053FamilyControlID' TEXT NOT NULL,
	'SP80053ControlID' TEXT NOT NULL,
	'SP80053ControlName' TEXT NOT NULL,
	'SP80053ControlFamilyIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053Control_SP80053ControlFamily' FOREIGN KEY ('SP80053ControlFamilyIndex') REFERENCES 'SP80053ControlFamily' ('SP80053ControlFamilyIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'SP80053ControlClass'
(
	'SP80053ControlClassIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ControlClassID' INTEGER NULL,
	'SP80053ControlClassName' TEXT NULL,
	'SP80053ControlFamilyIndex' INTEGER NULL
)
;

CREATE TABLE 'SP80053ControlDetail'
(
	'SP80053ControlDetailIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053ControlFamilyControlDetailID' TEXT NULL,
	'SP80053ControlDetailID' TEXT NOT NULL,
	'SP80053ControlDetailSubtitle' TEXT NULL,
	'SP80053ControlDetailDescription' TEXT NOT NULL,
	'SP80053ControlDetailPriority' INTEGER NULL,
	'SP80053ControlDetailAssurance' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineLow' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineMod' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineHigh' INTEGER NOT NULL,
	'SP80053ControlIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053ControlDetail_SP80053Control' FOREIGN KEY ('SP80053ControlIndex') REFERENCES 'SP80053Control' ('SP80053ControlIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

CREATE TABLE 'SP80053ControlFamily'
(
	'SP80053ControlFamilyIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ID' TEXT NOT NULL,
	'SP80053ControlFamilyID' TEXT NOT NULL,
	'SP80053ControlFamilyName' TEXT NOT NULL,
	'SP80053ControlFamilyFIPS200MinReq' TEXT NULL,
	'SP80053ControlClassIndex' INTEGER NOT NULL,
	CONSTRAINT 'FK_SP80053ControlFamily_SP80053ControlClass' FOREIGN KEY ('SP80053ControlClassIndex') REFERENCES 'SP80053ControlClass' ('SP80053ControlClassIndex') ON DELETE Set Null ON UPDATE Cascade
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_SP80053Control_SP80053ControlFamily'
 ON 'SP80053Control' ('SP80053ControlFamilyIndex' ASC)
;

CREATE INDEX 'IXFK_SP80053ControlDetail_SP80053Control'
 ON 'SP80053ControlDetail' ('SP80053ControlIndex' ASC)
;

CREATE INDEX 'IXFK_SP80053ControlFamily_SP80053ControlClass'
 ON 'SP80053ControlFamily' ('SP80053ControlClassIndex' ASC)
;
