/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 01-Sep-2020 4:39:41 PM 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

/* Drop Views */

DROP VIEW IF EXISTS 'CSFPFView'
;

DROP VIEW IF EXISTS 'CSFRMFView'
;

DROP VIEW IF EXISTS 'CSFSP80053RMFPFView'
;

DROP VIEW IF EXISTS 'CSFSP80053View'
;

DROP VIEW IF EXISTS 'CSFView'
;

DROP VIEW IF EXISTS 'PFView'
;

DROP VIEW IF EXISTS 'RMFView'
;

DROP VIEW IF EXISTS 'SP80053View'
;

/* Drop Tables */

DROP TABLE IF EXISTS 'NIST-CSFCategory'
;

DROP TABLE IF EXISTS 'NIST-CSFFunction'
;

DROP TABLE IF EXISTS 'NIST-CSF-PF'
;

DROP TABLE IF EXISTS 'NIST-CSF-RMF'
;

DROP TABLE IF EXISTS 'NIST-CSF-SP800-53'
;

DROP TABLE IF EXISTS 'NIST-CSFSubcategory'
;

DROP TABLE IF EXISTS 'NIST-FIPS200'
;

DROP TABLE IF EXISTS 'NIST-PFCategory'
;

DROP TABLE IF EXISTS 'NIST-PFFunction'
;

DROP TABLE IF EXISTS 'NIST-PFSubcategory'
;

DROP TABLE IF EXISTS 'NIST-Publication'
;

DROP TABLE IF EXISTS 'NIST-RMFStep'
;

DROP TABLE IF EXISTS 'NIST-RMFTask'
;

DROP TABLE IF EXISTS 'NIST-SP800-53Control'
;

DROP TABLE IF EXISTS 'NIST-SP800-53ControlClass'
;

DROP TABLE IF EXISTS 'NIST-SP800-53ControlDetail'
;

DROP TABLE IF EXISTS 'NIST-SP800-53ControlDetailRelated'
;

DROP TABLE IF EXISTS 'NIST-SP800-53ControlDetailSupplementalGuidance'
;

DROP TABLE IF EXISTS 'NIST-SP800-53ControlFamily'
;

/* Create Tables with Primary and Foreign Keys, Check and Unique Constraints */

CREATE TABLE 'NIST-CSFCategory'
(
	'CSFCategoryID' TEXT NOT NULL PRIMARY KEY,
	'CSFCategoryName' TEXT NOT NULL,
	'CSFCategoryDescription' TEXT NOT NULL,
	'CSFFunctionID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-CSFCategory_NIST-CSFFunction' FOREIGN KEY ('CSFFunctionID') REFERENCES 'NIST-CSFFunction' ('CSFFunctionID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-CSFFunction'
(
	'CSFFunctionID' TEXT NOT NULL PRIMARY KEY,
	'CSFFunctionName' TEXT NOT NULL,
	'CSFFunctionDescription' TEXT NOT NULL,
	'NISTPublicationID' TEXT NULL,
	CONSTRAINT 'FK_NIST-CSFFunction_NIST-Publication' FOREIGN KEY ('NISTPublicationID') REFERENCES 'NIST-Publication' ('NISTPublicationID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-CSF-PF'
(
	'CSFPFIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFSubcategoryID' TEXT NOT NULL,
	'PFSubcategoryID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-CSF-PF_NIST-CSFSubcategory' FOREIGN KEY ('CSFSubcategoryID') REFERENCES 'NIST-CSFSubcategory' ('CSFSubcategoryID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_NIST-CSF-PF_NIST-PFSubcategory' FOREIGN KEY ('PFSubcategoryID') REFERENCES 'NIST-PFSubcategory' ('PFSubcategoryID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-CSF-RMF'
(
	'CSFRMFIndex' INTEGER NOT NULL PRIMARY KEY,
	'CSFSubcategoryID' TEXT NOT NULL,
	'RMFTaskID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-CSF-RMF_NIST-CSFSubcategory' FOREIGN KEY ('CSFSubcategoryID') REFERENCES 'NIST-CSFSubcategory' ('CSFSubcategoryID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_NIST-CSF-RMF_NIST-RMFTask' FOREIGN KEY ('RMFTaskID') REFERENCES 'NIST-RMFTask' ('RMFTaskID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-CSF-SP800-53'
(
	'CSFSP80053Index' INTEGER NOT NULL PRIMARY KEY,
	'CSFSubcategoryID' TEXT NOT NULL,
	'SP80053ControlDetailID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-CSF-SP800-53_NIST-CSFSubcategory' FOREIGN KEY ('CSFSubcategoryID') REFERENCES 'NIST-CSFSubcategory' ('CSFSubcategoryID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_NIST-CSF-SP800-53_NIST-SP800-53ControlDetail' FOREIGN KEY ('SP80053ControlDetailID') REFERENCES 'NIST-SP800-53ControlDetail' ('SP80053ControlDetailID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-CSFSubcategory'
(
	'CSFSubcategoryID' TEXT NOT NULL PRIMARY KEY,
	'CSFSubcategoryDescription' TEXT NOT NULL,
	'CSFCategoryID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-CSFSubcategory_NIST-CSFCategory' FOREIGN KEY ('CSFCategoryID') REFERENCES 'NIST-CSFCategory' ('CSFCategoryID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-FIPS200'
(
	'FIPS200ID' TEXT NOT NULL PRIMARY KEY,
	'FIPS200MinReq' TEXT NULL,
	'SP80053ControlFamilyID' TEXT NOT NULL
)
;

CREATE TABLE 'NIST-PFCategory'
(
	'PFCategoryID' TEXT NOT NULL PRIMARY KEY,
	'PFCategoryName' TEXT NOT NULL,
	'PFCategoryDescription' TEXT NOT NULL,
	'PFFunctionID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-PFCategory_NIST-PFFunction' FOREIGN KEY ('PFFunctionID') REFERENCES 'NIST-PFFunction' ('PFFunctionID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-PFFunction'
(
	'PFFunctionID' TEXT NOT NULL PRIMARY KEY,
	'PFFunctionName' TEXT NOT NULL,
	'PFFunctionDescription' TEXT NOT NULL,
	'NISTPublicationID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-PFFunction_NIST-Publication' FOREIGN KEY ('NISTPublicationID') REFERENCES 'NIST-Publication' ('NISTPublicationID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-PFSubcategory'
(
	'PFSubcategoryID' TEXT NOT NULL PRIMARY KEY,
	'PFSubcategoryDescription' TEXT NOT NULL,
	'PFCategoryID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-PFSubcategory_NIST-PFCategory' FOREIGN KEY ('PFCategoryID') REFERENCES 'NIST-PFCategory' ('PFCategoryID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-Publication'
(
	'NISTPublicationID' TEXT NOT NULL PRIMARY KEY,
	'NISTPublicationName' TEXT NOT NULL,
	'NISTPublicationCommonName' TEXT NOT NULL,
	'NISTPublicationVersion' TEXT NULL,
	'NISTPublicationLink' TEXT NOT NULL
)
;

CREATE TABLE 'NIST-RMFStep'
(
	'RMFStepID' TEXT NOT NULL PRIMARY KEY,
	'RMFStepName' TEXT NOT NULL,
	'RMFStepDescription' TEXT NOT NULL,
	'NISTPublicationID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-RMFStep_NIST-Publication' FOREIGN KEY ('NISTPublicationID') REFERENCES 'NIST-Publication' ('NISTPublicationID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-RMFTask'
(
	'RMFTaskID' TEXT NOT NULL PRIMARY KEY,
	'RMFTaskName' TEXT NOT NULL,
	'RMFTaskDescription' TEXT NOT NULL,
	'RMFTaskTier' TEXT NULL,
	'RMFStepID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-RMFTask_NIST-RMFStep' FOREIGN KEY ('RMFStepID') REFERENCES 'NIST-RMFStep' ('RMFStepID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-SP800-53Control'
(
	'SP80053ControlID' TEXT NOT NULL PRIMARY KEY,
	'SP80053ControlName' TEXT NOT NULL,
	'SP80053ControlPriority' TEXT NULL,
	'SP80053ControlFamilyID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-SP800-53Control_NIST-SP800-53ControlFamily' FOREIGN KEY ('SP80053ControlFamilyID') REFERENCES 'NIST-SP800-53ControlFamily' ('SP80053ControlFamilyID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-SP800-53ControlClass'
(
	'SP80053ControlClassName' TEXT NOT NULL PRIMARY KEY,
	'NISTPublicationID' TEXT NOT NULL,
	CONSTRAINT 'FK_NIST-SP800-53ControlClass_NIST-Publication' FOREIGN KEY ('NISTPublicationID') REFERENCES 'NIST-Publication' ('NISTPublicationID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-SP800-53ControlDetail'
(
	'SP80053ControlDetailID' TEXT NOT NULL PRIMARY KEY,
	'SP80053ControlDetailEnhancementID' TEXT NULL,
	'SP80053ControlDetailCardinalOrdering' INTEGER NULL,
	'SP80053ControlDetailEnhancementName' TEXT NULL,
	'SP80053ControlDetailShortName' TEXT NULL,
	'SP80053ControlDetailDescription' TEXT NOT NULL,
	'SP80053ControlDetailAssignment' TEXT NULL,
	'SP80053ControlDetailTier' TEXT NULL,
	'SP80053ControlDetailSupplementalGuidanceIndex' INTEGER NULL,
	'SP80053ControlDetailReferenceIndex' INTEGER NULL,
	'SP80053ControlDetailAssurance' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineLow' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineMod' INTEGER NOT NULL,
	'SP80053ControlDetailBaselineHigh' INTEGER NOT NULL,
	'SP80053ControlID' TEXT NOT NULL,
	'SP80053ControlSupplementalGuidanceIndex' INTEGER NULL,
	CONSTRAINT 'FK_NIST-SP800-53ControlDetail_NIST-SP800-53Control' FOREIGN KEY ('SP80053ControlID') REFERENCES 'NIST-SP800-53Control' ('SP80053ControlID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_NIST-SP800-53ControlDetail_NIST-SP800-53ControlDetailSupplementalGuidance' FOREIGN KEY ('SP80053ControlSupplementalGuidanceIndex') REFERENCES 'NIST-SP800-53ControlDetailSupplementalGuidance' ('SP80053ControlSupplementalGuidanceIndex') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-SP800-53ControlDetailRelated'
(
	'SP80053ControlDetailRelatedIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ControlDetailID' TEXT NOT NULL,
	'SP80053ControlID' TEXT NOT NULL,
	'SP80053ControlFamilyID' TEXT NULL,
	CONSTRAINT 'FK_NIST-SP800-53ControlDetailRelated_NIST-SP800-53ControlDetail' FOREIGN KEY ('SP80053ControlDetailID') REFERENCES 'NIST-SP800-53ControlDetail' ('SP80053ControlDetailID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_NIST-SP800-53ControlDetailRelated_NIST-SP800-53ControlFamily' FOREIGN KEY ('SP80053ControlFamilyID') REFERENCES 'NIST-SP800-53ControlFamily' ('SP80053ControlFamilyID') ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE 'NIST-SP800-53ControlDetailSupplementalGuidance'
(
	'SP80053ControlSupplementalGuidanceIndex' INTEGER NOT NULL PRIMARY KEY,
	'SP80053ControlSupplementalGuidance' TEXT NOT NULL
)
;

CREATE TABLE 'NIST-SP800-53ControlFamily'
(
	'SP80053ControlFamilyID' TEXT NOT NULL PRIMARY KEY,
	'SP80053ControlClassName' TEXT NULL,
	'SP80053ControlFamilyName' TEXT NOT NULL,
	'FIPS200ID' TEXT NULL,
	CONSTRAINT 'FK_NIST-SP800-53ControlFamily_NIST-FIPS200' FOREIGN KEY ('FIPS200ID') REFERENCES 'NIST-FIPS200' ('FIPS200ID') ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT 'FK_NIST-SP800-53ControlFamily_NIST-SP800-53ControlClass' FOREIGN KEY ('SP80053ControlClassName') REFERENCES 'NIST-SP800-53ControlClass' ('SP80053ControlClassName') ON DELETE No Action ON UPDATE No Action
)
;

/* Create Indexes and Triggers */

CREATE INDEX 'IXFK_NIST-CSFCategory_NIST-CSFFunction'
 ON 'NIST-CSFCategory' ('CSFFunctionID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSFFunction_NIST-Publication'
 ON 'NIST-CSFFunction' ('NISTPublicationID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSF-PF_NIST-CSFSubcategory'
 ON 'NIST-CSF-PF' ('CSFSubcategoryID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSF-PF_NIST-PFSubcategory'
 ON 'NIST-CSF-PF' ('PFSubcategoryID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSF-RMF_NIST-CSFSubcategory'
 ON 'NIST-CSF-RMF' ('CSFSubcategoryID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSF-RMF_NIST-RMFTask'
 ON 'NIST-CSF-RMF' ('RMFTaskID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSF-SP800-53_NIST-CSFSubcategory'
 ON 'NIST-CSF-SP800-53' ('CSFSubcategoryID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSF-SP800-53_NIST-SP800-53ControlDetail'
 ON 'NIST-CSF-SP800-53' ('SP80053ControlDetailID' ASC)
;

CREATE INDEX 'IXFK_NIST-CSFSubcategory_NIST-CSFCategory'
 ON 'NIST-CSFSubcategory' ('CSFCategoryID' ASC)
;

CREATE INDEX 'IXFK_NIST-PFCategory_NIST-PFFunction'
 ON 'NIST-PFCategory' ('PFFunctionID' ASC)
;

CREATE INDEX 'IXFK_NIST-PFFunction_NIST-Publication'
 ON 'NIST-PFFunction' ('NISTPublicationID' ASC)
;

CREATE INDEX 'IXFK_NIST-PFSubcategory_NIST-PFCategory'
 ON 'NIST-PFSubcategory' ('PFCategoryID' ASC)
;

CREATE INDEX 'IXFK_NIST-RMFStep_NIST-Publication'
 ON 'NIST-RMFStep' ('NISTPublicationID' ASC)
;

CREATE INDEX 'IXFK_NIST-RMFTask_NIST-RMFStep'
 ON 'NIST-RMFTask' ('RMFStepID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53Control_NIST-SP800-53ControlFamily'
 ON 'NIST-SP800-53Control' ('SP80053ControlFamilyID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlClass_NIST-Publication'
 ON 'NIST-SP800-53ControlClass' ('NISTPublicationID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlDetail_NIST-SP800-53Control'
 ON 'NIST-SP800-53ControlDetail' ('SP80053ControlID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlDetail_NIST-SP800-53ControlDetailSupplementalGuidance'
 ON 'NIST-SP800-53ControlDetail' ('SP80053ControlSupplementalGuidanceIndex' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlDetailRelated_NIST-SP800-53ControlDetail'
 ON 'NIST-SP800-53ControlDetailRelated' ('SP80053ControlDetailID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlDetailRelated_NIST-SP800-53ControlFamily'
 ON 'NIST-SP800-53ControlDetailRelated' ('SP80053ControlFamilyID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlFamily_NIST-FIPS200'
 ON 'NIST-SP800-53ControlFamily' ('FIPS200ID' ASC)
;

CREATE INDEX 'IXFK_NIST-SP800-53ControlFamily_NIST-SP800-53ControlClass'
 ON 'NIST-SP800-53ControlFamily' ('SP80053ControlClassName' ASC)
;

/* Create Views */

CREATE VIEW 'CSFPFView' AS 
SELECT CSFView.CSFID,
       CSFFunctionName,
       CSFFunctionDescription,
       CSFCategoryName,
       CSFCategoryDescription,
       CSFSubcategoryDescription,
       PFView.PFID,
       PFFunctionName,
       PFFunctionDescription,
       PFCategoryName,
       PFCategoryDescription,
       PFSubcategoryDescription
  FROM CSFView
       LEFT JOIN
       [NIST-CSF-PF] AS csfpf ON CSFView.CSFSubcategoryIndex = csfpf.CSFSubcategoryIndex
       LEFT JOIN
       PFView ON csfpf.PFSubcategoryIndex = PFView.PFSubcategoryIndex
;


CREATE VIEW 'CSFRMFView' AS 
SELECT CSFView.CSFID,
       CSFFunctionName,
       CSFFunctionDescription,
       CSFCategoryName,
       CSFCategoryDescription,
       CSFSubcategoryDescription,
       RMFView.RMFID,
       RMFStepName,
       RMFStepDescription,
       RMFTaskName,
       RMFTaskDescription,
       RMFTaskTier
  FROM CSFView
       LEFT JOIN
       [NIST-CSF-RMF] AS csfrmf ON CSFView.CSFSubcategoryIndex = csfrmf.CSFSubcategoryIndex
       LEFT JOIN
       RMFView ON csfrmf.RMFTaskIndex = RMFView.RMFTaskIndex
;


CREATE VIEW 'CSFSP80053RMFPFView' AS 
SELECT CSFView.CSFID,
       CSFFunctionName,
       CSFFunctionDescription,
       CSFCategoryName,
       CSFCategoryDescription,
       CSFSubcategoryDescription,
       SP80053View.SP80053ID,
       SP80053ControlFamilyName,
       FIPS200MinReq,
       SP80053ControlName,
       SP80053ControlDetailShortTitle,
       SP80053ControlDetailDescription,
       SP80053ControlDetailAssignment,
       SP80053ControlDetailDesignation,
       SP80053ControlDetailTier,
       SP80053ControlDetailPriority,
       SP80053ControlDetailBaselineLow,
       SP80053ControlDetailBaselineMod,
       SP80053ControlDetailBaselineHigh,
       RMFView.RMFID,
       RMFStepName,
       RMFStepDescription,
       RMFTaskName,
       RMFTaskDescription,
       PFView.PFID,
       PFFunctionName,
       PFFunctionDescription,
       PFCategoryName,
       PFCategoryDescription,
       PFSubcategoryDescription
  FROM CSFView
       LEFT JOIN
       [NIST-CSF-SP800-53] AS csfsp80053 ON CSFView.CSFSubcategoryIndex = csfsp80053.CSFSubcategoryIndex
       LEFT JOIN
       SP80053View ON csfsp80053.SP80053ControlDetailIndex = SP80053View.SP80053ControlDetailIndex
       LEFT JOIN
       [NIST-CSF-RMF] AS csfrmf ON CSFView.CSFSubcategoryIndex = csfrmf.CSFSubcategoryIndex
       LEFT JOIN
       RMFView ON csfrmf.RMFTaskIndex = RMFView.RMFTaskIndex
       LEFT JOIN
       [NIST-CSF-PF] AS csfpf ON CSFView.CSFSubcategoryIndex = csfpf.CSFSubcategoryIndex
       LEFT JOIN
       PFView ON csfpf.PFSubcategoryIndex = PFView.PFSubcategoryIndex
 ORDER BY SP80053ControlName
;


CREATE VIEW 'CSFSP80053View' AS 
SELECT CSFView.CSFID,
       CSFFunctionName,
       CSFFunctionDescription,
       CSFCategoryName,
       CSFCategoryDescription,
       CSFSubcategoryDescription,
       SP80053View.SP80053ID,
       SP80053ControlFamilyName,
       FIPS200MinReq,
       SP80053ControlName,
       SP80053ControlDetailShortTitle,
       SP80053ControlDetailDescription,
       SP80053ControlDetailAssignment,
       SP80053ControlDetailDesignation,
       SP80053ControlDetailTier,
       SP80053ControlDetailPriority,
       SP80053ControlDetailBaselineLow,
       SP80053ControlDetailBaselineMod,
       SP80053ControlDetailBaselineHigh
  FROM CSFView
       LEFT JOIN
       [NIST-CSF-SP800-53] AS csfsp80053 ON CSFView.CSFSubcategoryIndex = csfsp80053.CSFSubcategoryIndex
       LEFT JOIN
       SP80053View ON csfsp80053.SP80053ControlDetailIndex = SP80053View.SP80053ControlDetailIndex
 ORDER BY SP80053ControlName
;


CREATE VIEW 'CSFView' AS 
SELECT subcategory.CSFSubcategoryIndex,
       subcategory.CSFID,
       CSFFunctionName,
       CSFFunctionDescription,
       CSFCategoryName,
       CSFCategoryDescription,
       CSFSubcategoryDescription
  FROM [NIST-CSFFunction] AS function
       INNER JOIN
       [NIST-CSFCategory] AS category ON function.CSFFunctionIndex = category.CSFFunctionIndex
       INNER JOIN
       [NIST-CSFSubcategory] AS subcategory ON category.CSFCategoryIndex = subcategory.CSFCategoryIndex
 ORDER BY function.CSFFunctionIndex,
          CSFCategoryName ASC
;


CREATE VIEW 'PFView' AS 
SELECT subcategory.CSFSubcategoryIndex,
       subcategory.CSFID,
       CSFFunctionName,
       CSFFunctionDescription,
       CSFCategoryName,
       CSFCategoryDescription,
       CSFSubcategoryDescription
  FROM [NIST-CSFFunction] AS function
       INNER JOIN
       [NIST-CSFCategory] AS category ON function.CSFFunctionIndex = category.CSFFunctionIndex
       INNER JOIN
       [NIST-CSFSubcategory] AS subcategory ON category.CSFCategoryIndex = subcategory.CSFCategoryIndex
 ORDER BY function.CSFFunctionIndex,
          CSFCategoryName ASC
;


CREATE VIEW 'RMFView' AS 
SELECT RMFTaskIndex,
       task.RMFID,
       RMFStepName,
       RMFStepDescription,
       RMFTaskName,
       RMFTaskDescription,
       RMFTaskTier
  FROM [NIST-RMFStep] AS step
       INNER JOIN
       [NIST-RMFTask] AS task ON step.RMFStepIndex = task.RMFStepIndex
;


CREATE VIEW 'SP80053View' AS 
SELECT SP80053ControlDetailIndex,
       detail.SP80053ID,
       SP80053ControlFamilyName,
       FIPS200MinReq,
       SP80053ControlName,
       detail.SP80053ControlDetailShortTitle,
       SP80053ControlDetailDescription,
       SP80053ControlDetailAssignment,
       SP80053ControlDetailDesignation,
       SP80053ControlDetailTier,
       SP80053ControlDetailPriority,
       SP80053ControlDetailBaselineLow,
       SP80053ControlDetailBaselineMod,
       SP80053ControlDetailBaselineHigh
  FROM [NIST-SP800-53ControlFamily] AS family
       INNER JOIN
       [NIST-SP800-53Control] AS control ON family.SP80053ControlFamilyIndex = control.SP80053ControlFamilyIndex
       INNER JOIN
       [NIST-SP800-53ControlDetail] AS detail ON control.SP80053ControlIndex = detail.SP80053ControlIndex
 ORDER BY SP80053ControlFamilyName,
          SP80053ControlName ASC
;

